//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("bilgimYokModel", "FK_kaynak_gazete", "gazete", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(bilgimyok.com.gazete), "kaynak", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bilgimyok.com.kaynak), true)]
[assembly: EdmRelationshipAttribute("bilgimYokModel", "FK_haber_kaynak", "kaynak", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(bilgimyok.com.kaynak), "haber", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bilgimyok.com.haber), true)]
[assembly: EdmRelationshipAttribute("bilgimYokModel", "FK_log_haber", "haber", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(bilgimyok.com.haber), "log", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bilgimyok.com.log), true)]
[assembly: EdmRelationshipAttribute("bilgimYokModel", "FK_kaynak_kategori", "kategori", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(bilgimyok.com.kategori), "kaynak", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bilgimyok.com.kaynak), true)]

#endregion

namespace bilgimyok.com
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class bilgimYokEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new bilgimYokEntities object using the connection string found in the 'bilgimYokEntities' section of the application configuration file.
        /// </summary>
        public bilgimYokEntities() : base("name=bilgimYokEntities", "bilgimYokEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new bilgimYokEntities object.
        /// </summary>
        public bilgimYokEntities(string connectionString) : base(connectionString, "bilgimYokEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new bilgimYokEntities object.
        /// </summary>
        public bilgimYokEntities(EntityConnection connection) : base(connection, "bilgimYokEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gazete> gazete
        {
            get
            {
                if ((_gazete == null))
                {
                    _gazete = base.CreateObjectSet<gazete>("gazete");
                }
                return _gazete;
            }
        }
        private ObjectSet<gazete> _gazete;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<haber> haber
        {
            get
            {
                if ((_haber == null))
                {
                    _haber = base.CreateObjectSet<haber>("haber");
                }
                return _haber;
            }
        }
        private ObjectSet<haber> _haber;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<kategori> kategori
        {
            get
            {
                if ((_kategori == null))
                {
                    _kategori = base.CreateObjectSet<kategori>("kategori");
                }
                return _kategori;
            }
        }
        private ObjectSet<kategori> _kategori;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<kaynak> kaynak
        {
            get
            {
                if ((_kaynak == null))
                {
                    _kaynak = base.CreateObjectSet<kaynak>("kaynak");
                }
                return _kaynak;
            }
        }
        private ObjectSet<kaynak> _kaynak;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<log> log
        {
            get
            {
                if ((_log == null))
                {
                    _log = base.CreateObjectSet<log>("log");
                }
                return _log;
            }
        }
        private ObjectSet<log> _log;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gazete EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogazete(gazete gazete)
        {
            base.AddObject("gazete", gazete);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the haber EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohaber(haber haber)
        {
            base.AddObject("haber", haber);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the kategori EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTokategori(kategori kategori)
        {
            base.AddObject("kategori", kategori);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the kaynak EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTokaynak(kaynak kaynak)
        {
            base.AddObject("kaynak", kaynak);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the log EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolog(log log)
        {
            base.AddObject("log", log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bilgimYokModel", Name="gazete")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gazete : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gazete object.
        /// </summary>
        /// <param name="gazete_id">Initial value of the gazete_id property.</param>
        /// <param name="gazete_ismi">Initial value of the gazete_ismi property.</param>
        /// <param name="gazete_logo">Initial value of the gazete_logo property.</param>
        public static gazete Creategazete(global::System.Int32 gazete_id, global::System.String gazete_ismi, global::System.String gazete_logo)
        {
            gazete gazete = new gazete();
            gazete.gazete_id = gazete_id;
            gazete.gazete_ismi = gazete_ismi;
            gazete.gazete_logo = gazete_logo;
            return gazete;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gazete_id
        {
            get
            {
                return _gazete_id;
            }
            set
            {
                if (_gazete_id != value)
                {
                    Ongazete_idChanging(value);
                    ReportPropertyChanging("gazete_id");
                    _gazete_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("gazete_id");
                    Ongazete_idChanged();
                }
            }
        }
        private global::System.Int32 _gazete_id;
        partial void Ongazete_idChanging(global::System.Int32 value);
        partial void Ongazete_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gazete_ismi
        {
            get
            {
                return _gazete_ismi;
            }
            set
            {
                Ongazete_ismiChanging(value);
                ReportPropertyChanging("gazete_ismi");
                _gazete_ismi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gazete_ismi");
                Ongazete_ismiChanged();
            }
        }
        private global::System.String _gazete_ismi;
        partial void Ongazete_ismiChanging(global::System.String value);
        partial void Ongazete_ismiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gazete_logo
        {
            get
            {
                return _gazete_logo;
            }
            set
            {
                Ongazete_logoChanging(value);
                ReportPropertyChanging("gazete_logo");
                _gazete_logo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gazete_logo");
                Ongazete_logoChanged();
            }
        }
        private global::System.String _gazete_logo;
        partial void Ongazete_logoChanging(global::System.String value);
        partial void Ongazete_logoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bilgimYokModel", "FK_kaynak_gazete", "kaynak")]
        public EntityCollection<kaynak> kaynak
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<kaynak>("bilgimYokModel.FK_kaynak_gazete", "kaynak");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<kaynak>("bilgimYokModel.FK_kaynak_gazete", "kaynak", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bilgimYokModel", Name="haber")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class haber : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new haber object.
        /// </summary>
        /// <param name="haber_id">Initial value of the haber_id property.</param>
        /// <param name="haber_resim">Initial value of the haber_resim property.</param>
        /// <param name="haber_basligi">Initial value of the haber_basligi property.</param>
        /// <param name="haber_icerigi">Initial value of the haber_icerigi property.</param>
        /// <param name="haber_link">Initial value of the haber_link property.</param>
        public static haber Createhaber(global::System.Int32 haber_id, global::System.String haber_resim, global::System.String haber_basligi, global::System.String haber_icerigi, global::System.String haber_link)
        {
            haber haber = new haber();
            haber.haber_id = haber_id;
            haber.haber_resim = haber_resim;
            haber.haber_basligi = haber_basligi;
            haber.haber_icerigi = haber_icerigi;
            haber.haber_link = haber_link;
            return haber;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 haber_id
        {
            get
            {
                return _haber_id;
            }
            set
            {
                if (_haber_id != value)
                {
                    Onhaber_idChanging(value);
                    ReportPropertyChanging("haber_id");
                    _haber_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("haber_id");
                    Onhaber_idChanged();
                }
            }
        }
        private global::System.Int32 _haber_id;
        partial void Onhaber_idChanging(global::System.Int32 value);
        partial void Onhaber_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> kaynak_id
        {
            get
            {
                return _kaynak_id;
            }
            set
            {
                Onkaynak_idChanging(value);
                ReportPropertyChanging("kaynak_id");
                _kaynak_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kaynak_id");
                Onkaynak_idChanged();
            }
        }
        private Nullable<global::System.Int32> _kaynak_id;
        partial void Onkaynak_idChanging(Nullable<global::System.Int32> value);
        partial void Onkaynak_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String haber_resim
        {
            get
            {
                return _haber_resim;
            }
            set
            {
                Onhaber_resimChanging(value);
                ReportPropertyChanging("haber_resim");
                _haber_resim = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("haber_resim");
                Onhaber_resimChanged();
            }
        }
        private global::System.String _haber_resim;
        partial void Onhaber_resimChanging(global::System.String value);
        partial void Onhaber_resimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String haber_basligi
        {
            get
            {
                return _haber_basligi;
            }
            set
            {
                Onhaber_basligiChanging(value);
                ReportPropertyChanging("haber_basligi");
                _haber_basligi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("haber_basligi");
                Onhaber_basligiChanged();
            }
        }
        private global::System.String _haber_basligi;
        partial void Onhaber_basligiChanging(global::System.String value);
        partial void Onhaber_basligiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String haber_icerigi
        {
            get
            {
                return _haber_icerigi;
            }
            set
            {
                Onhaber_icerigiChanging(value);
                ReportPropertyChanging("haber_icerigi");
                _haber_icerigi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("haber_icerigi");
                Onhaber_icerigiChanged();
            }
        }
        private global::System.String _haber_icerigi;
        partial void Onhaber_icerigiChanging(global::System.String value);
        partial void Onhaber_icerigiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String haber_link
        {
            get
            {
                return _haber_link;
            }
            set
            {
                Onhaber_linkChanging(value);
                ReportPropertyChanging("haber_link");
                _haber_link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("haber_link");
                Onhaber_linkChanged();
            }
        }
        private global::System.String _haber_link;
        partial void Onhaber_linkChanging(global::System.String value);
        partial void Onhaber_linkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> haber_tiklanma
        {
            get
            {
                return _haber_tiklanma;
            }
            set
            {
                Onhaber_tiklanmaChanging(value);
                ReportPropertyChanging("haber_tiklanma");
                _haber_tiklanma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("haber_tiklanma");
                Onhaber_tiklanmaChanged();
            }
        }
        private Nullable<global::System.Int32> _haber_tiklanma;
        partial void Onhaber_tiklanmaChanging(Nullable<global::System.Int32> value);
        partial void Onhaber_tiklanmaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ekleme_tarihi
        {
            get
            {
                return _ekleme_tarihi;
            }
            set
            {
                Onekleme_tarihiChanging(value);
                ReportPropertyChanging("ekleme_tarihi");
                _ekleme_tarihi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ekleme_tarihi");
                Onekleme_tarihiChanged();
            }
        }
        private Nullable<global::System.DateTime> _ekleme_tarihi;
        partial void Onekleme_tarihiChanging(Nullable<global::System.DateTime> value);
        partial void Onekleme_tarihiChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bilgimYokModel", "FK_haber_kaynak", "kaynak")]
        public kaynak kaynak
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kaynak>("bilgimYokModel.FK_haber_kaynak", "kaynak").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kaynak>("bilgimYokModel.FK_haber_kaynak", "kaynak").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<kaynak> kaynakReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kaynak>("bilgimYokModel.FK_haber_kaynak", "kaynak");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<kaynak>("bilgimYokModel.FK_haber_kaynak", "kaynak", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bilgimYokModel", "FK_log_haber", "log")]
        public EntityCollection<log> log
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<log>("bilgimYokModel.FK_log_haber", "log");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<log>("bilgimYokModel.FK_log_haber", "log", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bilgimYokModel", Name="kategori")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class kategori : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new kategori object.
        /// </summary>
        /// <param name="kategori_id">Initial value of the kategori_id property.</param>
        /// <param name="kategori_ismi">Initial value of the kategori_ismi property.</param>
        public static kategori Createkategori(global::System.Int32 kategori_id, global::System.String kategori_ismi)
        {
            kategori kategori = new kategori();
            kategori.kategori_id = kategori_id;
            kategori.kategori_ismi = kategori_ismi;
            return kategori;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kategori_id
        {
            get
            {
                return _kategori_id;
            }
            set
            {
                if (_kategori_id != value)
                {
                    Onkategori_idChanging(value);
                    ReportPropertyChanging("kategori_id");
                    _kategori_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("kategori_id");
                    Onkategori_idChanged();
                }
            }
        }
        private global::System.Int32 _kategori_id;
        partial void Onkategori_idChanging(global::System.Int32 value);
        partial void Onkategori_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String kategori_ismi
        {
            get
            {
                return _kategori_ismi;
            }
            set
            {
                Onkategori_ismiChanging(value);
                ReportPropertyChanging("kategori_ismi");
                _kategori_ismi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("kategori_ismi");
                Onkategori_ismiChanged();
            }
        }
        private global::System.String _kategori_ismi;
        partial void Onkategori_ismiChanging(global::System.String value);
        partial void Onkategori_ismiChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bilgimYokModel", "FK_kaynak_kategori", "kaynak")]
        public EntityCollection<kaynak> kaynak
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<kaynak>("bilgimYokModel.FK_kaynak_kategori", "kaynak");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<kaynak>("bilgimYokModel.FK_kaynak_kategori", "kaynak", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bilgimYokModel", Name="kaynak")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class kaynak : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new kaynak object.
        /// </summary>
        /// <param name="kaynak_id">Initial value of the kaynak_id property.</param>
        public static kaynak Createkaynak(global::System.Int32 kaynak_id)
        {
            kaynak kaynak = new kaynak();
            kaynak.kaynak_id = kaynak_id;
            return kaynak;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kaynak_id
        {
            get
            {
                return _kaynak_id;
            }
            set
            {
                if (_kaynak_id != value)
                {
                    Onkaynak_idChanging(value);
                    ReportPropertyChanging("kaynak_id");
                    _kaynak_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("kaynak_id");
                    Onkaynak_idChanged();
                }
            }
        }
        private global::System.Int32 _kaynak_id;
        partial void Onkaynak_idChanging(global::System.Int32 value);
        partial void Onkaynak_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gazete_id
        {
            get
            {
                return _gazete_id;
            }
            set
            {
                Ongazete_idChanging(value);
                ReportPropertyChanging("gazete_id");
                _gazete_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gazete_id");
                Ongazete_idChanged();
            }
        }
        private Nullable<global::System.Int32> _gazete_id;
        partial void Ongazete_idChanging(Nullable<global::System.Int32> value);
        partial void Ongazete_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> kategori_id
        {
            get
            {
                return _kategori_id;
            }
            set
            {
                Onkategori_idChanging(value);
                ReportPropertyChanging("kategori_id");
                _kategori_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kategori_id");
                Onkategori_idChanged();
            }
        }
        private Nullable<global::System.Int32> _kategori_id;
        partial void Onkategori_idChanging(Nullable<global::System.Int32> value);
        partial void Onkategori_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rss_link
        {
            get
            {
                return _rss_link;
            }
            set
            {
                Onrss_linkChanging(value);
                ReportPropertyChanging("rss_link");
                _rss_link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rss_link");
                Onrss_linkChanged();
            }
        }
        private global::System.String _rss_link;
        partial void Onrss_linkChanging(global::System.String value);
        partial void Onrss_linkChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bilgimYokModel", "FK_kaynak_gazete", "gazete")]
        public gazete gazete
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gazete>("bilgimYokModel.FK_kaynak_gazete", "gazete").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gazete>("bilgimYokModel.FK_kaynak_gazete", "gazete").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<gazete> gazeteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gazete>("bilgimYokModel.FK_kaynak_gazete", "gazete");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<gazete>("bilgimYokModel.FK_kaynak_gazete", "gazete", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bilgimYokModel", "FK_haber_kaynak", "haber")]
        public EntityCollection<haber> haber
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<haber>("bilgimYokModel.FK_haber_kaynak", "haber");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<haber>("bilgimYokModel.FK_haber_kaynak", "haber", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bilgimYokModel", "FK_kaynak_kategori", "kategori")]
        public kategori kategori
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kategori>("bilgimYokModel.FK_kaynak_kategori", "kategori").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kategori>("bilgimYokModel.FK_kaynak_kategori", "kategori").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<kategori> kategoriReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kategori>("bilgimYokModel.FK_kaynak_kategori", "kategori");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<kategori>("bilgimYokModel.FK_kaynak_kategori", "kategori", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bilgimYokModel", Name="log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new log object.
        /// </summary>
        /// <param name="log_id">Initial value of the log_id property.</param>
        public static log Createlog(global::System.Int32 log_id)
        {
            log log = new log();
            log.log_id = log_id;
            return log;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 log_id
        {
            get
            {
                return _log_id;
            }
            set
            {
                if (_log_id != value)
                {
                    Onlog_idChanging(value);
                    ReportPropertyChanging("log_id");
                    _log_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("log_id");
                    Onlog_idChanged();
                }
            }
        }
        private global::System.Int32 _log_id;
        partial void Onlog_idChanging(global::System.Int32 value);
        partial void Onlog_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_adresi
        {
            get
            {
                return _ip_adresi;
            }
            set
            {
                Onip_adresiChanging(value);
                ReportPropertyChanging("ip_adresi");
                _ip_adresi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_adresi");
                Onip_adresiChanged();
            }
        }
        private global::System.String _ip_adresi;
        partial void Onip_adresiChanging(global::System.String value);
        partial void Onip_adresiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String browser_adi
        {
            get
            {
                return _browser_adi;
            }
            set
            {
                Onbrowser_adiChanging(value);
                ReportPropertyChanging("browser_adi");
                _browser_adi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("browser_adi");
                Onbrowser_adiChanged();
            }
        }
        private global::System.String _browser_adi;
        partial void Onbrowser_adiChanging(global::System.String value);
        partial void Onbrowser_adiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> haber_id
        {
            get
            {
                return _haber_id;
            }
            set
            {
                Onhaber_idChanging(value);
                ReportPropertyChanging("haber_id");
                _haber_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("haber_id");
                Onhaber_idChanged();
            }
        }
        private Nullable<global::System.Int32> _haber_id;
        partial void Onhaber_idChanging(Nullable<global::System.Int32> value);
        partial void Onhaber_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tiklama_zamani
        {
            get
            {
                return _tiklama_zamani;
            }
            set
            {
                Ontiklama_zamaniChanging(value);
                ReportPropertyChanging("tiklama_zamani");
                _tiklama_zamani = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tiklama_zamani");
                Ontiklama_zamaniChanged();
            }
        }
        private Nullable<global::System.DateTime> _tiklama_zamani;
        partial void Ontiklama_zamaniChanging(Nullable<global::System.DateTime> value);
        partial void Ontiklama_zamaniChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bilgimYokModel", "FK_log_haber", "haber")]
        public haber haber
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<haber>("bilgimYokModel.FK_log_haber", "haber").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<haber>("bilgimYokModel.FK_log_haber", "haber").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<haber> haberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<haber>("bilgimYokModel.FK_log_haber", "haber");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<haber>("bilgimYokModel.FK_log_haber", "haber", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bilgimYokModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
